version: '3'

x-templates:
  agent_centos7_x86_64:
    &agent_centos7_x86_64
    image: harbor.einscat.com:10011/library/centos7:x86_64
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  agent_ubuntu2004_amd64:
    &agent_ubuntu2004_amd64
    image: harbor.einscat.com:10011/library/ubuntu2004:amd64
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

services:

  chaos-1:
    container_name: chaos-1
    hostname: "chaos-1"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.1
      chaos_net_2:
        ipv4_address: 172.20.40.1
    ports:
      - "10000:10000"
      - "10001:18080"
      - "10002:27001"
      - "10003:3306"
    volumes:
      - "~/shared:/root/shared"
    <<: *agent_centos7_x86_64

  chaos-2:
    container_name: chaos-2
    hostname: "chaos-2"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.2
      chaos_net_2:
        ipv4_address: 172.20.40.2
    ports:
      - "10004:10000"
      - "10005:18080"
      - "10006:27001"
      - "10007:3306"
    volumes:
      - "~/shared:/root/shared"
    <<: *agent_centos7_x86_64

  chaos-3:
    container_name: chaos-3
    hostname: "chaos-3"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.3
      chaos_net_2:
        ipv4_address: 172.20.40.3
    ports:
      - "10008:10000"
      - "10009:18080"
      - "10010:27001"
      - "10011:3306"
    volumes:
      - "~/shared:/root/shared"
    <<: *agent_centos7_x86_64

  chaos-4:
    container_name: chaos-4
    hostname: "chaos-4"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.4
      chaos_net_2:
        ipv4_address: 172.20.40.4
    <<: *agent_centos7_x86_64

  chaos-5:
    container_name: chaos-5
    hostname: "chaos-5"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.5
      chaos_net_2:
        ipv4_address: 172.20.40.5
    <<: *agent_centos7_x86_64

  chaos-6:
    container_name: chaos-6
    hostname: "chaos-6"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.6
      chaos_net_2:
        ipv4_address: 172.20.40.6
    ports:
      - "10020:10000"
      - "10021:18080"
      - "10022:27001"
      - "10023:3306"
    volumes:
      - "~/shared:/root/shared"
    <<: *agent_ubuntu2004_amd64

  chaos-7:
    container_name: chaos-7
    hostname: "chaos-7"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.7
      chaos_net_2:
        ipv4_address: 172.20.40.7
    <<: *agent_ubuntu2004_amd64

  chaos-8:
    container_name: chaos-8
    hostname: "chaos-8"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.8
      chaos_net_2:
        ipv4_address: 172.20.40.8
    <<: *agent_ubuntu2004_amd64

networks:
  chaos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.30.0/24
          gateway: 172.20.30.254
  chaos_net_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.40.0/24
          gateway: 172.20.40.254

