version: '3'

x-templates:
  agent_centos7_x86_64:
    &agent_centos7_x86_64
    image: harbor.einscat.com:10011/library/centos7:x86_64
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  agent_ubuntu2004_amd64:
    &agent_ubuntu2004_amd64
    image: harbor.einscat.com:10011/library/ubuntu2004:amd64
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

services:

  vm-1:
    container_name: vm-1
    hostname: "vm-1"
    networks:
      vm_net:
        ipv4_address: 172.20.30.1
      vm_net_2:
        ipv4_address: 172.20.40.1
    ports:
      - "20000:10000"
      - "20001:18080"
      - "20002:27001"
      - "20003:3306"
      - "16379:6379"
    volumes:
      - "/opt/shared:/opt/shared"
    <<: *agent_centos7_x86_64

  vm-2:
    container_name: vm-2
    hostname: "vm-2"
    networks:
      vm_net:
        ipv4_address: 172.20.30.2
      vm_net_2:
        ipv4_address: 172.20.40.2
    ports:
      - "20004:10000"
      - "20005:18080"
      - "20006:27001"
      - "20007:3306"
      - "26379:6379"
    <<: *agent_centos7_x86_64

  vm-3:
    container_name: vm-3
    hostname: "vm-3"
    networks:
      vm_net:
        ipv4_address: 172.20.30.3
      vm_net_2:
        ipv4_address: 172.20.40.3
    ports:
      - "20008:10000"
      - "20009:18080"
      - "20010:27001"
      - "20011:3306"
      - "36379:6379"
    <<: *agent_centos7_x86_64

  vm-4:
    container_name: vm-4
    hostname: "vm-4"
    networks:
      vm_net:
        ipv4_address: 172.20.30.4
      vm_net_2:
        ipv4_address: 172.20.40.4
    ports:
      - "20008:10000"
      - "20009:18080"
      - "20010:27001"
      - "20011:3306"
      - "46379:6379"
    <<: *agent_centos7_x86_64

  vm-5:
    container_name: vm-5
    hostname: "vm-5"
    networks:
      vm_net:
        ipv4_address: 172.20.30.5
      vm_net_2:
        ipv4_address: 172.20.40.5
    ports:
      - "20008:10000"
      - "20009:18080"
      - "20010:27001"
      - "20011:3306"
      - "56379:6379"
    <<: *agent_centos7_x86_64

  vm-6:
    container_name: vm-6
    hostname: "vm-6"
    networks:
      vm_net:
        ipv4_address: 172.20.30.6
      vm_net_2:
        ipv4_address: 172.20.40.6
    ports:
      - "20012:10000"
      - "20013:18080"
      - "20014:27001"
      - "20015:3306"
    <<: *agent_ubuntu2004_amd64

  vm-7:
    container_name: vm-7
    hostname: "vm-7"
    networks:
      vm_net:
        ipv4_address: 172.20.30.7
      vm_net_2:
        ipv4_address: 172.20.40.7
    ports:
      - "20016:10000"
      - "20017:18080"
      - "20018:27001"
      - "20019:3306"
    <<: *agent_ubuntu2004_amd64

  vm-8:
    container_name: vm-8
    hostname: "vm-8"
    networks:
      vm_net:
        ipv4_address: 172.20.30.8
      vm_net_2:
        ipv4_address: 172.20.40.8
    ports:
      - "20020:10000"
      - "20021:18080"
      - "20022:27001"
      - "20023:3306"
    <<: *agent_ubuntu2004_amd64

  vm-9:
    container_name: vm-9
    hostname: "vm-9"
    networks:
      vm_net:
        ipv4_address: 172.20.30.9
      vm_net_2:
        ipv4_address: 172.20.40.9
    ports:
      - "20024:10000"
      - "20025:18080"
      - "20026:27001"
      - "20027:3306"
    <<: *agent_ubuntu2004_amd64

  vm-10:
    container_name: vm-10
    hostname: "vm-10"
    networks:
      vm_net:
        ipv4_address: 172.20.30.10
      vm_net_2:
        ipv4_address: 172.20.40.10
    ports:
      - "20028:10000"
      - "20029:18080"
      - "20030:27001"
      - "20031:3306"
    <<: *agent_ubuntu2004_amd64

networks:
  vm_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.30.0/24
          gateway: 172.20.30.254
  vm_net_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.40.0/24
          gateway: 172.20.40.254

