version: '3'

x-templates:
  agent_centos7_altarch:
    &agent_centos7_altarch
    image: harbor.einscat.com:10011/library/centos7:altarch
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

services:

  chaos-1:
    container_name: chaos-1
    hostname: "chaos-1"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.1
      chaos_net_2:
        ipv4_address: 172.20.40.1
    ports:
      - "20000:10000"
      - "20001:18080"
      - "20002:27001"
      - "20003:3306"
    volumes:
      - "~/workspace:/root/workspace"
    <<: *agent_centos7_altarch

  chaos-2:
    container_name: chaos-2
    hostname: "chaos-2"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.2
      chaos_net_2:
        ipv4_address: 172.20.40.2
    ports:
      - "20004:10000"
      - "20005:18080"
      - "20006:27001"
      - "20007:3306"
    <<: *agent_centos7_altarch

  chaos-3:
    container_name: chaos-3
    hostname: "chaos-3"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.3
      chaos_net_2:
        ipv4_address: 172.20.40.3
    ports:
      - "20008:10000"
      - "20009:18080"
      - "20010:27001"
      - "20011:3306"
    <<: *agent_centos7_altarch

  chaos-4:
    container_name: chaos-4
    hostname: "chaos-4"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.4
      chaos_net_2:
        ipv4_address: 172.20.40.4
    ports:
      - "20012:10000"
      - "20013:18080"
      - "20014:27001"
      - "20015:3306"
    <<: *agent_centos7_altarch

  chaos-5:
    container_name: chaos-5
    hostname: "chaos-5"
    networks:
      chaos_net:
        ipv4_address: 172.20.30.5
      chaos_net_2:
        ipv4_address: 172.20.40.5
    ports:
      - "20016:10000"
      - "20017:18080"
      - "20018:27001"
      - "20019:3306"
    <<: *agent_centos7_altarch

networks:
  chaos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.30.0/24
          gateway: 172.20.30.254
  chaos_net_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.40.0/24
          gateway: 172.20.40.254

