version: '3'

x-templates:
  agent_centos8_aarch64:
    &agent_centos8_aarch64
    image: harbor.einscat.com:10011/library/centos8:aarch64
    privileged: true
    stdin_open: true
    tty: true
    extra_hosts:
      - "docker-registry:192.168.18.20"
    cap_add:
      - ALL
    working_dir: /opt
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

services:

  vm-1:
    container_name: vm-1
    hostname: "vm-1"
    networks:
      vm_net:
        ipv4_address: 172.20.30.1
      vm_net_2:
        ipv4_address: 172.20.40.1
    ports:
      - "20000:10000"
      - "20001:18080"
      - "20002:27001"
      - "20003:3306"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "~/workspace:/root/workspace"
    <<: *agent_centos8_aarch64

  vm-2:
    container_name: vm-2
    hostname: "vm-2"
    networks:
      vm_net:
        ipv4_address: 172.20.30.2
      vm_net_2:
        ipv4_address: 172.20.40.2
    ports:
      - "20004:10000"
      - "20005:18080"
      - "20006:27001"
      - "20007:3306"
    <<: *agent_centos8_aarch64

  vm-3:
    container_name: vm-3
    hostname: "vm-3"
    networks:
      vm_net:
        ipv4_address: 172.20.30.3
      vm_net_2:
        ipv4_address: 172.20.40.3
    ports:
      - "20008:10000"
      - "20009:18080"
      - "20010:27001"
      - "20011:3306"
    <<: *agent_centos8_aarch64

  vm-4:
    container_name: vm-4
    hostname: "vm-4"
    networks:
      vm_net:
        ipv4_address: 172.20.30.4
      vm_net_2:
        ipv4_address: 172.20.40.4
    ports:
      - "20012:10000"
      - "20013:18080"
      - "20014:27001"
      - "20015:3306"
    <<: *agent_centos8_aarch64

  vm-5:
    container_name: vm-5
    hostname: "vm-5"
    networks:
      vm_net:
        ipv4_address: 172.20.30.5
      vm_net_2:
        ipv4_address: 172.20.40.5
    ports:
      - "20016:10000"
      - "20017:18080"
      - "20018:27001"
      - "20019:3306"
    <<: *agent_centos8_aarch64

networks:
  vm_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.30.0/24
          gateway: 172.20.30.254
  vm_net_2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.40.0/24
          gateway: 172.20.40.254

